(function() {var implementors = {
"concert":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"concert/struct.Concert.html\" title=\"struct concert::Concert\">Concert</a>"]],
"crowdsale":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"crowdsale/io/struct.IcoState.html\" title=\"struct crowdsale::io::IcoState\">IcoState</a>"]],
"dao":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"dao/struct.Proposal.html\" title=\"struct dao::Proposal\">Proposal</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"dao/struct.Member.html\" title=\"struct dao::Member\">Member</a>"]],
"dao_light":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"dao_light/struct.Proposal.html\" title=\"struct dao_light::Proposal\">Proposal</a>"]],
"dex_factory":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"dex_factory/struct.Factory.html\" title=\"struct dex_factory::Factory\">Factory</a>"]],
"dex_pair":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"dex_pair/struct.Pair.html\" title=\"struct dex_pair::Pair\">Pair</a>"]],
"game_of_chance":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"game_of_chance/struct.GOCInit.html\" title=\"struct game_of_chance::GOCInit\">GOCInit</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"game_of_chance/struct.GOCState.html\" title=\"struct game_of_chance::GOCState\">GOCState</a>"]],
"gear_lib":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"gear_lib/fungible_token/state/struct.FTState.html\" title=\"struct gear_lib::fungible_token::state::FTState\">FTState</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"gear_lib/multitoken/io/struct.TokenMetadata.html\" title=\"struct gear_lib::multitoken::io::TokenMetadata\">TokenMetadata</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"gear_lib/multitoken/io/struct.Token.html\" title=\"struct gear_lib::multitoken::io::Token\">Token</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"gear_lib/multitoken/state/struct.MTKState.html\" title=\"struct gear_lib::multitoken::state::MTKState\">MTKState</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"gear_lib/non_fungible_token/state/struct.NFTState.html\" title=\"struct gear_lib::non_fungible_token::state::NFTState\">NFTState</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"gear_lib/non_fungible_token/token/struct.Token.html\" title=\"struct gear_lib::non_fungible_token::token::Token\">Token</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"gear_lib/non_fungible_token/token/struct.TokenMetadata.html\" title=\"struct gear_lib::non_fungible_token::token::TokenMetadata\">TokenMetadata</a>"]],
"identity":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"identity/struct.IdentityStorage.html\" title=\"struct identity::IdentityStorage\">IdentityStorage</a>"]],
"multisig_wallet":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"multisig_wallet/struct.MultisigWallet.html\" title=\"struct multisig_wallet::MultisigWallet\">MultisigWallet</a>"]],
"multitoken":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"multitoken/struct.SimpleMTK.html\" title=\"struct multitoken::SimpleMTK\">SimpleMTK</a>"]],
"nft":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"nft/struct.NFT.html\" title=\"struct nft::NFT\">NFT</a>"]],
"on_chain_nft":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"on_chain_nft/struct.OnChainNFT.html\" title=\"struct on_chain_nft::OnChainNFT\">OnChainNFT</a>"]],
"rentable_nft":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"rentable_nft/struct.NFT.html\" title=\"struct rentable_nft::NFT\">NFT</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"rentable_nft/struct.UserInfo.html\" title=\"struct rentable_nft::UserInfo\">UserInfo</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"rentable_nft/struct.RentableNFT.html\" title=\"struct rentable_nft::RentableNFT\">RentableNFT</a>"]],
"staking":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"staking/io/struct.Staker.html\" title=\"struct staking::io::Staker\">Staker</a>"]]
};if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()